server:
  port: 8081
  http2:
    enabled: true
  shutdown: graceful

spring:
  application:
    name: consumer-service
  rabbitmq:
    addresses: amqps://fvawagon:uIVAEFlZCv3j9TcPJx7s95ncnIWXyRnB@woodpecker.rmq.cloudamqp.com/fvawagon
  data:
    mongodb:
      host: localhost
      port: 27017
      database: signaldb
      authentication-database: admin
      username: consumer_user
      password: consumer_pass
  cloud:
    stream:
      function:
        definition: signalCreatedEventListener
      bindings:
        signalCreatedEventListener-in-0:
          destination: signal.v1.event.created
          group: signals
      rabbit:
        bindings:
          signalCreatedEventListener-in-0:
            consumer:
              auto-bind-dlq: true
