version: '3.2'
services:
  percona-mongodb:
    image: percona/percona-server-mongodb:5.0.13
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: signaldb
      MONGO_INITDB_ROOT_USERNAME: consumer_user
      MONGO_INITDB_ROOT_PASSWORD: consumer_pass
    networks:
      - percona-mongodb

networks:
  percona-mongodb:
